name: Email Batch Sender

on:
  schedule:
    # 9:00 AM IST -> 3:30 AM UTC
    - cron: "30 3 * * *"
    # 10:00 AM IST -> 4:30 AM UTC
    - cron: "30 4 * * *"
    # 1:00 PM IST -> 7:30 AM UTC
    - cron: "30 7 * * *"
    # 5:00 PM IST -> 11:30 AM UTC
    - cron: "30 11 * * *"

jobs:
  send-emails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run batch mail script
        run: python send_mail.py
